language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
script: python travistest.py
notifications:
  email:
    - sivadhanamjay@aptuz.com
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
