language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
script: python travistest.py
notifications:
  email:
    - sivadhanamjay@aptuz.com
addons:
  sauce_connect:
    username: "Siva1018"
    access_key: "Backspace9"
